name: mmm-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas>=1.3.0
  - numpy>=1.21.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - scikit-learn>=1.0.0
  - xgboost>=1.5.0
  - jupyter>=1.0.0
  - ipykernel>=6.0.0
  - plotly>=5.0.0
  - statsmodels>=0.13.0
  - pip
  - pip:
    - google-colab  # For Google Colab compatibility